<?php
$static.='<h1>About '.SITE_TITLE.'</h1><h5>Who\'s in charge?</h5>
<p>
Hot Dish is a collaboration of social media provider NewsCloud and Grist.org, the country\'s leading online source of environmental news. Hot Dish is made possible by a grant from the John S. and James L. Knight Foundation.
</p><p>
The goal of Hot Dish is to build a large and thriving community around climate change news and action. We all know climate change sucks, but Hot Dish is here to show how you and the people you know can actually do something about it. With the role of traditional media changing every day, you (and your friends) have more power than ever to shape both global conversation and global action on issues like climate change, especially with the help of digital social media platforms like Facebook.</p>
<h2>About NewsCloud</h2>
<p>
Launched in 2005, <a onclick="quickLog(\'extLink\',\'about\',0,\'http://www.newscloud.com\');" href="http://www.newscloud.com" target="_blank">NewsCloud</a> is a community-driven news aggregator and an open source solutions provider for social media. At the end of the project, NewsCloud will release the source code to these Facebook applications via open source license. Visit <a onclick="quickLog(\'extLink\',\'about\',0,\'http://www.newscloud.com/research\');" href="http://www.newscloud.com/research" target="_blank">www.newscloud.com/research</a> for more information.</p>
<h2>About Grist.org</h2>
<p>
With a fresh spin on environmental news and views, <a onclick="quickLog(\'extLink\',\'about\',0,\'http://www.grist.org\');" href="http://www.grist.org" target="_blank">Grist.org</a> informs, inspires, and links America\'s next generation of green activists. Founded in April 1999, Grist has developed the most recognizable voice in environmental journalism: funny, opinionated, and intelligent. Grist offers in-depth reporting, news analysis, opinions, and practical advice -- all tailored to inform, entertain, provoke, and encourage its readers to think creatively about environmental problems and solutions.</p>
<h2>About the John S. and James L. Knight Foundation</h2>
<p><a onclick="quickLog(\'extLink\',\'about\',0,\'http://www.knightfoundation.org\');" href="http://www.knightfoundation.org" target="_blank"><img border="0" src="'.URL_CALLBACK.'?p=cache&img=kf_logo_color_250px.jpg" style="float:right;" alt="Knight Foundation Logo" /></a>
The <a onclick="quickLog(\'extLink\',\'about\',0,\'http://www.knightfoundation.org\');" href="http://www.knightfoundation.org" target="_blank">John S. and James L. Knight Foundation</a> invests in journalism excellence worldwide and in the vitality of U.S. communities where the Knight brothers owned newspapers. Since 1950, the foundation has granted more than $400 million to advance quality journalism and freedom of expression. Knight Foundation focuses on projects with the potential to create transformational change.<br clear="all"/></p>';
	$static.='<h2>Site Credits</h2>'.
'<p>Design by <a onclick="quickLog(\'extLink\',\'about\',0,\'http://www.geoffco.com\');" href="http://www.geoffco.com">GeoffCo</a></p><p>Open source libraries used: Platform - <a href="http://www.debian.org/">Linux Debian</a>, <a href="http://www.apache.org/">Apache</a>, <a href="http://www.php.net/">PHP</a>, <a href="http://www.mysql.com/">MySQL</a>, RSS Parsing - <a href="http://simplepie.org">Simple Pie</a>, RSS Creator - Derived from <a href="http://www.feedcreator.org/">Feed Creator</a>, Web services parsing example uses the modified <a target="_cts" href="http://www.engageinteractive.com/mambo/index.php?option=content&task=view&id=3628&Itemid=10159">Saxy Parser</a> from <a href="http://www.phpflickr.com/" target="_cts">PHPFlickr</a>, <a href="http://javascript.crockford.com/jsmin2.php.txt" target="_cts">JSMinLib for PHP</a></p>';
	$static.='<br /><br />';
	
?>