<?php
	$static='<br /><h1>'.SITE_TITLE.' Frequently Asked Questions</h1><h5>Some of the most common questions we get are:</h5>'.
'<div class="bullet_list"><ul>' .
		'<li><strong>How do I know if I am eligible to win rewards?</strong> In order to be eligible for rewards, participants must be United States residents between the ages of 16 to 25 years old and opt in to the research study. Minors must have permission from a parent or guardian. Please see <a href="?p=tos" onclick="switchPage(\'static\',\'tos\');return false;">official rules</a> for complete details.</li>'.
 '<li><strong>Why is the reward program restricted?</strong> The Action Team is part of a voluntary research study of 16- to 25-year-olds conducted by University of Minnesota researchers on behalf of the Knight Foundation to learn more about engaging young people using social networks in current events. As this is a nonprofit study, our budget is limited. We apologize if you are not able to share in the rewards program. We hope you still enjoy the Hot Dish application.</li>'.
          '<li><strong>How do I add the Hot Dish application tab?</strong> Visit your profile page, then click the plus (+) sign to the right of the Wall, Info and Boxes tab. Then, select Hot Dish from the drop down menu.</li>'.
          '<li><strong>How do I add the Bookmark tool to my browser?</strong> Go to the Post a Story tab and drag the orange "Post to Hot Dish" button up to the links bar in your browser.'.
          '<li><strong>How do I allow Hot Dish to send me occasional email?</strong> Go to "Settings" and click on "Would you like to receive email from us through facebook? (50 pts)" and wait for the magic to happen.'.
          '<li><strong>How do I get SMS/text messages from Hot Dish?</strong> Click on "Settings" and then "Would you like to receive sms notifications from us through facebook? (50 pts)" and follow the instructions.'.
          '<li><strong>I completed something in a challenge awhile ago. Can I still get points?</strong> Unfortunately, only challenges completed after you have signed up for Hot Dish earn you points. You are a green superstar, though -- and there are plenty of other challenges for you to complete!'.
          '<li><strong>Wait, a trip to the Arctic is the grand prize? That is not green!</strong> True, frivolous jetsetting is a middle finger to the planet. But if you win the grand prize, your trip will open your eyes to the effects of climate change in a way like never before, and you\'ll have a chance to share your experience with readers at Hot Dish and Grist.org. Via the Knight Foundation sponsorship, Hot Dish will pay for up to $1,000 in CO<sup>2</sup> offsets for your trip. Quark Expeditions is committed to <a href="http://www.quarkexpeditions.com/environmental-commitment/overview" onclick="quickLog(\'extLink\',\'faq\',0,\'http://www.quarkexpeditions.com/environmental-commitment/overview\');" target="_blank">environmental responsibility</a> as well. This trip will bring to life stuff you may have only read about, and afterwards, you will likely be a more vocal advocate for Arctic conservation.'.
          '<li><strong>Why do I have to send you a screenshot of my profile to prove I did a challenge? Where is the trust, yo?</strong> While we would like to give you the benefit of the doubt, we also want to keep Hot Dish fair. Plus, the proof is in the pudding, and we love pudding!'.
          '<li><strong>So how do I take a screenshot?</strong> On a PC, press Print Screen and paste the image into Paint. Save it as a JPEG file. Then you can upload it on the challenge detail page. For more detailed instructions, <a href="http://www.wikihow.com/Take-a-Screenshot-in-Microsoft-Windows">go here</a>. On a Mac, simultaneously pressing Command-Shift-3 will save a screenshot as a file on the desktop. If it ends in PNG, open it in Preview and save it as a JPEG instead. Then you can upload it on the challenge detail page. For more detailed instructions, <a href="http://www.wikihow.com/Take-a-Screenshot-in-Mac-OS-X">go here</a>.'.
          '<li><strong>Where is the parental consent form for Action Team participation?</strong> You can <a href="'.URL_CALLBACK.'?p=cache&pdf=consentForm" target="_blank">download the consent form here</a>.'.
'<li><strong>Why do some people appear as Anonymous?</strong> Due to Facebook privacy settings, we cannot show you all Hot Dish users\' names and photos.'.
'<li><strong>Why is the reward program limited to U.S. residents?</strong> Anyone can participate in the Action Team, but unfortunately non-U.S. residents aren\'t eligible for rewards other than <a href="http://apps.facebook.com/hotdish/?p=cbd">free ringtones</a> from Center for Biological Diversity and <a href="http://apps.facebook.com/hotdish/?p=eqex">free shipping</a> from Equal Exchange. This is due to the legal complexities of running a contest and the limited budget of the research study, which is funded by a nonprofit grant. We apologize if you are not able to share in the rewards program. However, if an organization in your country wants to work with us to run an Action Team there, please contact us!</li>'.
'<li><strong>Why can\'t I invite more friends per day?</strong> We want you to be able to invite as many friends as you want, but Facebook puts a cap on this based on several different factors. The short version of the story is that this cap can change, and hopefully it will go up soon so you can invite more friends. Please follow up with your friends to get them to accept your invitations. This will help you in the Action Team contest and encourage Facebook to increase our daily limits.</li>'.          
'<li><strong>Why do some people have more voting power than others?</strong> Some people get more voting power than others, depending on how many points they have. For instance, if you vote up a story, it may translate into 6 votes if you are a fairly active user. We designed the system to allow the more active members to yield more influence in the editorial process.</li>'.
'</ul></div><!--end "bullet_list"--><br />';		
?>